apiVersion: v1
kind: Pod
metadata:
  name: storage-pod
spec:
  containers:
  - name: storage
    image: ubuntu                                                                                                                                                                                                      command: ["/bin/bash", "-ec", "while :; do sleep 2; done;"]
    volumeMounts:
    - mountPath: /data
      name: storage-volume
  volumes:
  - name: storage-volume
    persistentVolumeClaim:
      claimName: storage-pvc
