apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: iptables-tailer
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
